olaMundo = 'Hello World'

print(olaMundo)
print('------------------')
print(len(olaMundo))
print('------------------')
print(olaMundo[0])
print('------------------')
print(olaMundo[1:])
print('------------------')
print(olaMundo[:3])
print('------------------')
print(olaMundo[:])
print('------------------')
print(olaMundo[-1])
print('------------------')
print(olaMundo[:-1])
print('------------------')
print(olaMundo[::1])
print('------------------')
print(olaMundo[::2])
print('------------------')
print(olaMundo[::-1])
print('------------------')
print(olaMundo + 'concat')
print('------------------')
olaMundoNovo = olaMundo + 'concat'
print(olaMundoNovo)
print('------------------')
print(olaMundo*10)
print('------------------')
print(olaMundo.upper())
print('------------------')
print(olaMundo.lower())
print('------------------')
print(olaMundo.split())
print('------------------')
print('Insert another string with curly brackets: {}'.format('The inserted string'))
print('------------------')
